# Generated by Django 4.0.2 on 2022-02-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_beds_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
