# Generated by Django 4.0.2 on 2022-02-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_hospital_hospitalname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedtype1',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedtype2',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedtype3',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
