# Generated by Django 4.0.2 on 2022-02-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bed_bedtype1_alter_bed_bedtype2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatienBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtype', models.CharField(max_length=50)),
                ('hospitalcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
