# Generated by Django 4.0.2 on 2022-02-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patienbookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatienBookings',
            new_name='PB',
        ),
    ]
